// Query to calculate the total revenue generated by each restaurant

db.orders.aggregate([
    { $group: { 
        _id: "$restaurantId", 
        totalRevenue: { $sum: "$totalPrice" } 
    }},
    { $sort: { totalRevenue: -1 } }
]);